[versions]
micronaut-platform = "4.7.2"

[libraries]
micronaut-platform = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut-platform" }
micronaut-inject-java = { module = "io.micronaut:micronaut-inject-java" }
micronaut-test-junit5 = { module = "io.micronaut.test:micronaut-test-junit5" }
micronaut-data-processor = { module = "io.micronaut.data:micronaut-data-processor" }
micronaut-data-hibernate-jpa = { module = "io.micronaut.data:micronaut-data-hibernate-jpa" }
micronaut-jdbc-hikari = { module = "io.micronaut.sql:micronaut-jdbc-hikari" }
micronaut-liquibase = { module = "io.micronaut.liquibase:micronaut-liquibase" }
jul-to-slf4j = { module = "org.slf4j:jul-to-slf4j" }

h2 = { module = "com.h2database:h2" }
micronaut-serde-processor = { module = "io.micronaut.serde:micronaut-serde-processor" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client" }
micronaut-http-server-netty = { module = "io.micronaut:micronaut-http-server-netty" }
